#pragma once

#define MAX_CHARGE_TIME 5.0
#define MAX_CHANNEL_TIME 10.0
#define KNOCKED_DOWN_TIME 2.0

#define MAX_STORM_LIFETIME 10.0
#define STORM_UNIT_DISTANCE_FROM_PLAYER 250.0
#define STORM_UNIT_GAP 20.0 // degrees